name: Test OIDC-powered ECR image pull

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write          # required for OIDC
  contents: read           # required for actions/checkout if you use it

env:
  AWS_ECR_REGION: ${{ secrets.AWS_ECR_REGION }}
  AWS_ECR_ACCOUNT_ID: ${{ secrets.AWS_ECR_ACCOUNT_ID }}
  AWS_ECR_ROLE_NAME: ${{ secrets.AWS_ECR_ROLE_NAME }}
  AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
  AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  AWS_ECR_HCD_IMAGE_TAG: "1.2.1-early-preview"

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ECR_ACCOUNT_ID }}:role/${{ env.AWS_ECR_ROLE_NAME }}
          aws-region: ${{ env.AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull the image
        run: |
          docker pull $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$AWS_ECR_HCD_IMAGE_TAG

      - name: Assert success
        run: |
          echo "Image pulled successfully: $AWS_ECR_REGISTRY/$ECR_REPOSITORY:$AWS_ECR_HCD_IMAGE_TAG. Yo!"
