name: Run idiomatic pytest on HCD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    env:
      # for admin-related testing if enabled
      DO_IDIOMATIC_ADMIN_TESTS: ${{ secrets.DO_IDIOMATIC_ADMIN_TESTS }}
      # hardcoding the target DB
      DOCKER_COMPOSE_LOCAL_DATA_API: "yes"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run pytest
      run: |
        poetry run pytest tests/idiomatic
